### ISSUE TITLE
The tool shows KIlled 

### ISSUE THREAD

**Issue by josenikhid97** [computations/root_digger#10]
Hello @team_rootdigger

I have installed the root digger correctly as u  mentioned in the github page read me . but the problem now is the tool is showing the program has been killed while running at the initial step itself. it worked with the other datasets very well.the data set i used for running is sars covid datset (9499 sequences ).
![rd_error](https://user-images.githubusercontent.com/64956458/173046678-0eb355ee-e83e-4dde-99b7-3967443c8dd3.png)

waiting for you reply

**Comment by computations** [comment]
Ah, I see. It might be that the machine that is running root digger doesn't have enough memory to run an analysis on a data set this large. When we ran the analysis with COVID data for a paper, we used a machine with about 700 GB of memory. I'm not sure how much you need, but try using a machine with more memory.

**Comment by josenikhid97** [comment]
hello. Thank you for the quick reply .

your suggestion worked successfully, now i am able to run in it but it is taking longer time for 9500 sequences (lets say more than 15 hrs ). is there any fast way possible to do the rooting under UNREST model with this tool (may be some kind of flags to be mentioned before hand).

Thank you

**Comment by computations** [comment]
you can change the number of starting roots with `--min-roots` if you feel the current number of trials is too high. maybe this is sufficient for you?
