### ISSUE TITLE
Does root_digger print the log-likelihood values ?

### ISSUE THREAD

**Issue by josenikhid97** [computations/root_digger#11]
Hello @josephwb, @nathanweeks 

I was able to run the tool successfully, but is there any flags to be added for printing the log-likelihood values because i cant see any log-likelihood values on the terminal, all i can see is only the newick format and the inference time . is there any possible way to see the log-likelihood and also BIC values.

Best
Jose

**Comment by computations** [comment]
The LogLH should print right above the newick on the terminal in the log. The BIC you will have to calculate yourself for now. The number of parameters in the model is something like 

- For each partition:
  - 12 for the rate parameters
  - 3 for the frequencies
  - If invariant sites are enabled, add another parameter
  - If rate categories are enabled, add another parameter
- One more parameter for the root location

By default, for a single partition, the number of parameters then is 12 (subst rates) + 3 (frequencies) + 1 (rate categories) + 1 (root location) = 17.

**Comment by josenikhid97** [comment]
Okay, is it possible not to print the newick format (by using flags ) or any other way possible because it prints the entire screen and i cant see even if i scroll the pointer upwards.

**Comment by computations** [comment]
You can redirect the output to a file with `./rd ... > analysis.log` and then read the file

**Comment by josenikhid97** [comment]
okay thank you for the info and for the quick reply
