### ISSUE TITLE
Source directory does not contain CMakeLists.txt file 

### ISSUE THREAD

**Issue by linda5mith** [computations/root_digger#21]
Hi I'm having some problem building with cmake:

```
cd root_digger
mkdir build
cd build
cmake -B ~/programs/root_digger/build/ -S ~/programs/root_digger/
```
```

-- The C compiler identification is GNU 9.4.0
-- The CXX compiler identification is GNU 9.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Git: /usr/bin/git (found version "2.25.1") 
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found OpenMP_C: -fopenmp (found version "4.5") 
-- Found OpenMP_CXX: -fopenmp (found version "4.5") 
-- Found OpenMP: TRUE (found version "4.5")  
CMake Error at lib/CMakeLists.txt:2 (add_subdirectory):
  The source directory

    /home/administrator/programs/root_digger/lib/coraxlib

  does not contain a CMakeLists.txt file.
```

Seems like a silly error but usually when I specify path to build + source folders it works. 

Many thanks!

**Comment by computations** [comment]
Thanks for your interest in RootDigger!

It seems that you need to checkout the submodules. You can do this with

```
git submodule update --init --recursive
```

Let me know if that works.

**Comment by linda5mith** [comment]
Hey no problem, I find your documentation a bit confusing but I managed to get it installed!

This failed due to gitlab certificate out of date for coraxlib dependency:
`git clone --recursive https://github.com/computations/root_digger`

Solved by: 
```
sudo apt-get update
sudo apt-get install apt-transport-https ca-certificates -y
sudo update-ca-certificates

```
Then I installed libpacke/libpack (followed commands from [here](https://askubuntu.com/questions/417726/installing-a-comprehensive-lapack-implementation-under-ubuntu)): 
```
sudo apt-get install libblas-dev checkinstall
sudo apt-get install libblas-doc checkinstall
sudo apt-get install liblapacke-dev checkinstall
sudo apt-get install liblapack-doc checkinstall

```
I also installed coraxlib separately (not sure if this was necessary):
```
git clone https://codeberg.org/Exelixis-Lab/coraxlib.git
cd coraxlib
mkdir -p build && cd build
cmake ..
make
```
Then the `make` command worked as expected. 

Thanks :)

**Comment by computations** [comment]
Great to hear that. Thanks for your feedback on the documentation. I'll see if I can't rewrite it to be a bit clearer.

The cert issue with codeberg has been an ongoing issue, but I'm glad that you managed to resolve it :smile:

Closing this since everything seems to be working
