### ISSUE TITLE
cannot run RootDigger

### ISSUE THREAD

**Issue by zhangws119** [computations/root_digger#3]
Hi,
Thanks for sharing this great software. I've installed RootDigger on Ubuntu, but I cannot run it, could you help me to solve this problem? The details as follows:

###  (base) geobig@geobig-PowerEdge-T640:~/Users/Softwares/root_digger/root_digger/test/data$ /home/geobig/Users/Softwares/root_digger/root_digger/bin/rd -h
/home/geobig/Users/Softwares/root_digger/root_digger/bin/rd: unrecognized option '-h'
Usage: rd [options]
Version: v0.4.0-179-g4b8357d
Application Options:
    --msa [FILE]
           File containing the alignment.
    --tree [FILE]
           File containing the tree, with branch lengths.
    --partition [FILE]
           Optional file containing the partition specification.
           Format is the same as RAxML-NG partition file.
    --exhaustive
           Enable exhaustive mode. This will attempt to root a tree
           at every branch, and then report the results using LWR.
    --early-stop
           Enable early stopping. This will cause cause the search
           to terminate when the root placement is sufficently
           close for 2 consecutive iterations. How close they need
           to be is controled by brtol. Is enabled by default for
           search mode and disabled by default for exhaustive mode.
    --no-early-stop
           Force disable early stop.
    --seed [NUMBER]
           Random seed to use. Optional
    --rate-cats [NUMBER]
           Number of rate categories to use for the model. Default
           is 1.
    --invariant-sites
           Enable invariant sites. Default is off.
    --min-roots [NUMBER]
           Minimum number of roots to start from. Optional,
           Default is 1.
    --root-ratio [NUMBER]
           Proportion of potential starting roots to attempt
           Default is 0.01
    --atol [NUMBER]
           Root optmization stopping tolerance. Increase this to 
           improve results.Default is 1e-4
    --brtol [NUMBER]
           When early stop mode is enabled, this controls the
           distance required to trigger. Default is 1e-12
    --bfgstol [NUMBER]
           Tolerance for the BFGS steps. Default is 1e-7
    --factor [NUMBER]
           Factor for the BFGS steps. Default is 1e4
    --silent
           Suppress output except for the final tree
    --verbose
           Increase the verbosity level. Can be repeated to
           level further.
(base) geobig@geobig-PowerEdge-T640:~/Users/Softwares/root_digger/root_digger/test/data$ /home/geobig/Users/Softwares/root_digger/root_digger/bin/rd --msa /home/geobig/Users/Softwares/root_digger/root_digger/test/data/protein/140.phy --tree /home/geobig/Users/Softwares/root_digger/root_digger/test/data/tree/140.tree --no-early-stop
**[0.00] Running Root Digger
[0.00] Version: v0.4.0-179-g4b8357d
[0.00] Build Commit: 4b8357dc5136353e1b999707ced58281072086ff
[0.00] Build Date: 2020-02-23 13:49:04
[0.00] Started: 2020-02-24 10:20:28
[0.00] Seed: 2662287295
Segmentation fault (core dumped)**

Looking forward to hearing from you.

**Comment by computations** [comment]
Can you try again with DNA data? RootDigger does not support protein (the subst matrix has too many parameters to safely optimize).

**Comment by zhangws119** [comment]
> Can you try again with DNA data? RootDigger does not support protein (the subst matrix has too many parameters to safely optimize).

Thanks for your reply. I've tried the DNA data, and the results are as follows:

**(base) geobig@geobig-PowerEdge-T640:~/Users/Wensi/rd_test$ /home/geobig/Users/Softwares/root_digger/root_digger/bin/rd --msa /home/geobig/Users/Softwares/root_digger/root_digger/test/data/dna/10.fasta --tree /home/geobig/Users/Softwares/root_digger/root_digger/test/data/tree/10.tree --no-early-stop
[0.00] Running Root Digger
[0.00] Version: v0.4.0-179-g4b8357d
[0.00] Build Commit: 4b8357dc5136353e1b999707ced58281072086ff
[0.00] Build Date: 2020-02-23 13:49:04
[0.00] Started: 2020-02-25 15:34:02
[0.00] Seed: 1844146178
[0.01] Root 1/1
[11.10] Final LogLH: -12434.37782
(((h:0.983500,a:0.224900):0.416200,(c:0.540900,f:0.422200):0.785300):0.232087,((g:0.487400,(((i:0.569700,e:0.366600):0.602800,b:0.445900):0.099300,d:0.639600):0.825200):0.446100,j:0.854700):0.382013):0.0;
Inference took: 11.0995s**

But I am still confused about  'Final LogLH ...' part in my level. Would you please explain it for me?

**Comment by computations** [comment]
The `Final LogLH` is the log likelihood at of the final root placement and model parameters which maximizes the likelihood. You can use this number to compare results with other runs of root digger, or to other tools which compute a likelihood score (assuming they are made to be comparable with libpll/iq-tree). For more information, I would suggest Ziheng Yang's book _Computational Molecular Evolution_.

**Comment by zhangws119** [comment]
> The `Final LogLH` is the log likelihood at of the final root placement and model parameters which maximizes the likelihood. You can use this number to compare results with other runs of root digger, or to other tools which compute a likelihood score (assuming they are made to be comparable with libpll/iq-tree). For more information, I would suggest Ziheng Yang's book _Computational Molecular Evolution_.

Thanks a lot for your explanation.
